name: Terraform AWS deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'nginx-app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'nginx-app/**'

env:
  TF_VAR_aws_region: eu-central-1

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add git.epam.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan git.epam.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_aws_region }}
          role-to-assume: arn:aws:iam::038462790533:role/TerraformRole
          role-session-name: GitHubActionsSession
          role-skip-session-tagging: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./nginx-app

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=plan.tfplan
        continue-on-error: true
        working-directory: ./nginx-app

      - name: Terraform Apply
        if: |
          github.ref == 'refs/heads/main' && steps.plan.outcome == 'success' &&
          (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: terraform apply -auto-approve plan.tfplan
        working-directory: ./nginx-app